ENV_ESTRATEGIA = ["impulsivo", "exigente", "cauteloso", "aleatorio"]
ENV_QUANTIDADE_DE_PROPRIEDADES = 20
ENV_NUMERO_SIMULACOES = 300
ENV_FIM_DO_TEMPO_PARTIDA = 1000
ENV_Jogador_DINHEIRO = 300.0
ENV_Jogador_DINHEIRO_PARTIDA = 100.0
